const CONF = {
    TILE_SIZE: 16,
    CHAOS_FACTOR: 50,

    INDIVIDUAL_FOREST_CHANCE: 0.2,
    FOREST_SPAWN_RATE: 0.3,

    RIVER_SPAWN_RATE: 0.06,

    ARTIC_LOWER_LIMIT: 0.2,
    ARID_UPPER_LIMIT: 0.8,
};
